#!/opt/homebrew/bin/bash

/opt/homebrew/bin/fastfetch \
  --pipe \
  --structure Battery \
  --format json |
/opt/homebrew/bin/jq -r '
  .[]
  | select(.type == "Battery")
  | .result[0]
  | "Battery \(.capacity | round)% [\(.status | join(", "))]"
'
