#!/opt/homebrew/bin/bash

/opt/homebrew/bin/fastfetch \
  --pipe \
  --structure Wifi \
  --format json |
  /opt/homebrew/bin/jq -r '
    .[]
    | select(.type == "Wifi")
    | .result[0].conn
    | if .status != "Active" then
        "Wifi: Disconnected"
      else
        "Wifi: \(.ssid // "Unknown") (\(.signalQuality | round)%)"
      end
  '
