#!/opt/homebrew/bin/bash

/opt/homebrew/bin/fastfetch \
  --pipe \
  --structure Memory:Swap \
  --format json |
/opt/homebrew/bin/jq -r '
  def gib:
    . / 1073741824;

  def two_decimals:
    ((. * 100) | round) / 100;

  (.[] | select(.type == "Memory") | .result) as $mem |
  (.[] | select(.type == "Swap") | .result[0]) as $swap |

  "Memory: \(($mem.used | gib | two_decimals)) GiB / " +
  "\(($mem.total | gib | two_decimals)) GiB " +
  "(\(($mem.used * 100 / $mem.total) | round)%) | " +
  (
    if ($swap.total // 0) == 0 then
      "Swap: Unused"
    else
      "Swap: \(($swap.used | gib | two_decimals)) GiB / " +
      "\(($swap.total | gib | two_decimals)) GiB"
    end
  )
'
